data:
  directory: data
  filename: grade_data.xml

training:
  model_path: 'distilbert-base-uncased'
  batch_size: 8
  num_workers: 4
  train_percent: 100
  test_percent: 100
  max_lr: 1.e-5
  weight_decay: 1.e-5
  max_epochs: 15
  max_patience: 3
  num_labels: 4

eval:
  modeldir: cpu_trained_distilbert_split_after
